"""empty message

Revision ID: 85aaa2ae4178
Revises: 1c23b833cbb5
Create Date: 2019-04-11 11:42:11.313906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85aaa2ae4178'
down_revision = '1c23b833cbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
